export const emptyStateRoot = 'flex flex-col items-center justify-center text-center p-8 gap-3'
export const emptyStateIcon = 'text-gs-fg-subtle w-12 h-12'
export const emptyStateTitle = 'text-lg font-semibold text-gs-fg'
export const emptyStateDescription = 'text-sm text-gs-fg-muted max-w-[360px]'
export const emptyStateActions = 'flex gap-2 mt-1'
